#include <stdio.h>
int main(){
    int a;
    scanf("%d",&a);
    switch(a){
        case1:
        printf("31");
        break;
        case2:
        printf("28");
        break;
        case3:
        printf("31");
        break;
        case4:
        printf("30");
        break;
        case5:
        printf("31");
        break;
        case6:
        printf("30");
        break;
        case7:
        printf("31");
        break;
        case8:
        printf("30");
        break;
        case9:
        printf("31");
        break;
        case10:
        printf("30");
        break;
        case11:
        printf("31");
        break;
        case12:
        printf("30");
        break;
        default:
        printf("Invalid");
    }
}